default['CTJenkins']['isUrlTest'] = 'true'
default['CTJenkins']['testNowBaseUrl'] = ''
default['CTJenkins']['testNowUIUrl'] = ''
default['CTJenkins']['testNowUsername'] = ''
default['CTJenkins']['testNowPassword'] = ''
